[package]
name = "persistent-kv"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13"
regex = "1.1"
clap = "2.33.3"

[dev-dependencies]
tempfile = "3.2"

[[bin]]         
name = "persistent-kv-cli"    
path = "main.rs"
